import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@styles/Home.module.scss'

import SampleCard from '@components/SampleCard/SampleCard'
import CardAnim from '@components/CardAnim/CardAnim'
import Navbar from '@components/Navbar/Navbar'
import CardCarousel from '@components/CardCarousel/CardCarousel'
import { useState } from 'react'
import { Deck } from 'types/deck'
import { DeckCtx } from 'redux/deckContext'

const Home: NextPage = () => {

  const [deck, setDeck] = useState<Deck>(null);



  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DeckCtx.Provider value={[ deck, setDeck ]}>
        <main className={styles.main}>
          <Navbar />
          <CardCarousel />
          {/* <SampleCard/> */}
          {/* <CardAnim/> */}
        </main>


      </DeckCtx.Provider>

      <footer >
      </footer>
    </div>
  )
}

export default Home
