import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@styles/Home.module.scss'

import SampleCard from '@components/SampleCard/SampleCard'
import CardAnim from '@components/CardAnim/CardAnim'
import Navbar from '@components/Navbar/Navbar'
import CardCarousel from '@components/CardCarousel/CardCarousel'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar/>
        <CardCarousel/>
        {/* <SampleCard/> */}
        {/* <CardAnim/> */}
      </main>

      <footer >
      </footer>
    </div>
  )
}

export default Home
